module.exports = {
  USER: {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
  },
  CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
  CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
  UPDATE_STATE_CUSTOMER: 'UPDATE_STATE_CUSTOMER',
  FIND_CUSTOMER_SUCCESS: 'FIND_CUSTOMER_SUCCESS',
  FIND_CUSTOMER_FAILED: 'FIND_CUSTOMER_FAILED',
  CHARGE_MONEY_SUCCESS: 'CHARGE_MONEY_SUCCESS',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
};
